### ISSUE TITLE
Magic prevent DataContractSerializer to work on Windows Phone 8.1

### ISSUE THREAD

**Issue by bNobo** [demigor/kindofmagic#3]
Hi,

I have a weird exception when trying to serialize a class with a DataContractSerializer when there is a MagicAttribute class defined. The exception is:

`A first chance exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll
'App2.exe' (CoreCLR: .): Loaded 'C:\windows\system32\en-US\mscorlib.debug.resources.dll'. Module was built without symbols.
System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule module, RuntimeType caType)
   at System.Reflection.RuntimeModule.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Runtime.Serialization.DataContract.GetGlobalDataContractNamespace(String clrNs, ICustomAttributeProvider customAttribuetProvider)
   at System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace(Type type)
   at System.Runtime.Serialization.DataContract.GetNonDCTypeStableName(Type type)
   at System.Runtime.Serialization.DataContract.GetStableName(Type type, Boolean& hasDataContract)
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type)
   at System.Runtime.Serialization.ClassDataContract..ctor(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContractSerializer.get_RootContract()
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteStartObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
   at App2.MainPage.Button_Click(Object sender, RoutedEventArgs e)`

No matter if Magic attribute is applied or not on a class, its sole existence seems to make serialization failing.

If I remove the MagicAttribute class, serialization then works well. I have made a sample project to illustrate the problem: 

1) build, deploy and run, then click on the button => serialization work well
2) stop, uncomment "public class MagicAttribute..." and re-run => "serializer.WriteObject" fails

[App2.zip](https://github.com/demigor/kindofmagic/files/170164/App2.zip)

Strange uh ?

**Comment by demigor** [comment]
Fixed in 1.3.0 (In WinRT/UWP GeneratedCodeAttribute has been moved to another assembly)
